-- SQLite cannot alter column to NOT NULL directly
-- Instead, ensure app sets values, or recreate table if required
-- Example using table recreation:

---------------------------------
--CREATE TABLE devices_new (
--    id INTEGER PRIMARY KEY AUTOINCREMENT,
--    name TEXT NOT NULL,
--    client_id TEXT,
--   username TEXT NOT NULL,
--    password TEXT NOT NULL,
--    ...
--);
--INSERT INTO devices_new SELECT id, name, client_id, username, password, ... FROM devices;
--DROP TABLE devices;
--ALTER TABLE devices_new RENAME TO devices;
----------------------------------