--CREATE TABLE devices (
 --   id INTEGER PRIMARY KEY AUTOINCREMENT,
 --   name TEXT NOT NULL,
 --   protocol TEXT DEFAULT 'mqtt',
 --   host TEXT,
  --  port INTEGER DEFAULT 1883,
  --  client_id TEXT,
   -- username TEXT,
  --  password TEXT,
  --  mqtt_version TEXT,
  --  keep_alive INTEGER,
  --  auto_reconnect INTEGER DEFAULT 1,
  --  reconnect_period INTEGER,
  --  enable_tls INTEGER DEFAULT 0,
  --  status TEXT DEFAULT 'offline',
  --  is_connected INTEGER DEFAULT 0,
  --  user_id INTEGER,
   -- updated_at TEXT DEFAULT CURRENT_TIMESTAMP
--);
