--CREATE TABLE dashboards (
--    id INTEGER PRIMARY KEY AUTOINCREMENT,
--  name TEXT NOT NULL,
--    description TEXT,
--    is_template INTEGER DEFAULT 0,
--    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
--    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
--);
--CREATE TABLE dashboard_devices (
 --   id INTEGER PRIMARY KEY AUTOINCREMENT,
--  dashboard_id INTEGER,
--    device_id INTEGER,
--    friendly_name TEXT
--);
