--CREATE TABLE permissions (
  --  id INTEGER PRIMARY KEY AUTOINCREMENT,
  --  name TEXT NOT NULL UNIQUE,
  --  description TEXT
--);

--CREATE TABLE role_permissions (
  --  role_id INTEGER,
  --  permission_id INTEGER,
  --  PRIMARY KEY (role_id, permission_id)
--);
