"""Baseline migration

Revision ID: 3668f01c8c84
Revises: e96bb2871c2a
Create Date: 2025-10-24 11:10:18.869505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3668f01c8c84'
down_revision = 'e96bb2871c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendly_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('friendly_name')

    # ### end Alembic commands ###
