"""Add temperature, humidity, pressure columns to sensors

Revision ID: 6ab76fd26352
Revises: 3668f01c8c84
Create Date: 2025-10-25 11:27:41.968288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab76fd26352'
down_revision = '3668f01c8c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pressure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('payload',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('friendly_name')
        batch_op.drop_column('name')
        batch_op.drop_column('created_at')
        batch_op.drop_column('min_value')
        batch_op.drop_column('sensor_type')
        batch_op.drop_column('max_value')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sensor_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('min_value', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('friendly_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('payload',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('topic',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('pressure')
        batch_op.drop_column('humidity')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
